[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.f_flash = 80000000L
monitor_speed = 115200
; Flags for external 32.768 kHz crystal – these must be removed if you configure via menuconfig
; board_build.extra_flags = -DCONFIG_ESP32_RTC_CLOCK_SOURCE_EXTERNAL_CRYSTAL=y -DCONFIG_ESP32_RTC_XTAL_CAL_RTC_MUX=y